export { default as HomePage } from './HomePage'
export { default as RegisterPage } from './RegisterPage'
export { default as TestPage } from './TestPage'
export { default as NotFoundPage } from './NotFoundPage'
export { default as AddArticlePage } from './Articles/AddArticlePage'
export { default as ArticlesPage } from './Articles/ArticlesPage'